### PR TITLE
Allow developers to add devServer config

### PR DESCRIPTION
**Pull request by baranovxyz**
In webpack.config.js

### CODE REVIEW

**Comment by jvanbruegge** [comment]
There is a better fix for that. Move the user config at the bottom of the `configs/webpack.config.js`
Then it will overwrite the flavor config

**Comment by baranovxyz** [comment]
> There is a better fix for that. Move the user config at the bottom of the configs/webpack.config.js Then it will overwrite the flavor config

Moving from
```
module.exports = createConfig([
  customConfig(userConfig),
  tslint(),
  ...
])
```
to 
```
module.exports = createConfig([
  tslint(),
  ...,
  customConfig(userConfig)
])
```
Does not work for me...

**Comment by jvanbruegge** [comment]
Weird

**Comment by jvanbruegge** [comment]
Found the issue and fixed it, now the `userConfig` always overwrites predefined values

**Pull request closed without merging**
