### PR TITLE
Add new SPA template

### PR DESCRIPTION
**Pull request by jvanbruegge**
The current version is working, but there is still work left to do
- [x] Add tests for counter
- [x] add onionify initState wrapper to `cyclejs-test-helpers`
- [x] PR for `istanbul-instrumenter-loader` to fix webpack paths (https://github.com/webpack-contrib/istanbul-instrumenter-loader/pull/70, created a fork `istanbul-instrumenter-loader-fix`)
- [x] Add test for speaker
- [x] PR for `storageify` to add a custom debounce time (https://github.com/maiermic/cycle-storageify/pull/8)
- [x] PR for `cyclic-router` sink type (https://github.com/cyclejs-community/cyclic-router/pull/198)
- [x] PR for `cyclic-router` to make it a main wrapper (https://github.com/cyclejs-community/cyclic-router/pull/200)
- [x] Add test for app
- [x] Update README

- [ ] PR for `@cycle/storage` to add typings (https://github.com/cyclejs/storage/pull/26)

### CODE REVIEW

**Comment by jvanbruegge** [comment]
cc @SteveALee

**Comment by SteveALee** [comment]
I already updated the readme. Is more needed? I also tweaked the test but just noticed is broken due to a path error in import.

BTW - should we change the routes? I think `/` is good but other could be `/page2` or `/speaker`

**Comment by jvanbruegge** [comment]
I want to restructure the Readme a bit.
The tests were broken due to a path error, but coverage was not 100% any more, so I added two new tests.

Yes, I will change the route

**Comment by SteveALee** [comment]
One more thing for your list is to make sure create-cycle-app --flavor still works now repo changed

**Comment by SteveALee** [comment]
Thanks for doing tests. I can cross of my list :)

**Comment by jvanbruegge** [comment]
The package name stays the same, that's not a problem

**Comment by SteveALee** [comment]
Cool.

Am looking forward to the release. It should answer a few FAQs and help
with on-boarding. Thanks for encouragement and improvements.

**Comment by jvanbruegge** [comment]
A current version for trying out can be installed with
```
create-cycle-app test --flavor cycle-scripts-one-fits-all@beta
```

**Comment by jvanbruegge** [comment]
Coverage is now working for the whole codebase, not only the files that have tests.
Plus babel is not needed any more as a direct dependency (still indirect as the istanbul uses babel).
coverage

**Comment by jvanbruegge** [comment]
So, speaker coverage is now 100% too.
coverage2

**Comment by SteveALee** [comment]
Please update PR comment to 
`PR for cyclic-router sink type cyclejs-community/cyclic-router#198`

I stuck to the current convention of using the form `Stream<HistoryAction>` in the using code. Do you want related a PR to sync this one?

**Comment by jvanbruegge** [comment]
Yes, then i will sqash&merge

**Comment by jvanbruegge** [comment]
@SteveALee testing with `cyclic-router` is quite painful, so I opened https://github.com/cyclejs-community/cyclic-router/pull/200

**Comment by jvanbruegge** [comment]
So, now I'm just waiting to get merge rights on `@cycle/storage` and this can be merged

**Comment by SteveALee** [comment]
Wh00t

**Comment by SteveALee** [comment]
Yippee! I wonder how Github can give me notifications for releases? There aught to be a way

**Pull request merged**
